kind: Service
apiVersion: v1
metadata:
  name: jobmanager-webui
spec:
  type: "{{ .Values.service.type }}"
  selector:
    component: jobmanager
  ports:
    - port: 8081
      targetPort: 8081
      name: http
  